### ISSUE TITLE
Performance and scalability

### ISSUE THREAD

**Issue by xukai92** [zsteve/OptimalTransport.jl#9]
Thanks for a great package. 
I was hoping to use the Sinkhorn algorithm which I believe scales better than the EMD solver.
I did some quick benchmarks but found it was not the case.

```julia
using Distances, LinearAlgebra, OptimalTransport
using BenchmarkTools, Plots

function make_noisyprob(L, errorlevel)
    prob = ones(L)
    # Mimic Hamiltonian error
    prob += errorlevel * rand(L)
    return prob / norm(prob, 1)
end

function make_fakedata(dim, L, errorlevel)
    p = make_noisyprob(L, errorlevel)
    q = make_noisyprob(L, errorlevel)
    C = pairwise(SqEuclidean(), randn(dim, L), randn(dim, L))
    return p, q, C
end

dim = 10
Ls = 5:5:100
errorlevel = 0.01
ϵ = 0.1

ts_sinkhorn = map(Ls) do L
    p, q, C = make_fakedata(dim, L, errorlevel)
    @belapsed sinkhorn($p, $q, $C, $ϵ)
end

ts_emd = map(Ls) do L
    p, q, C = make_fakedata(dim, L, errorlevel)
    @belapsed emd($p, $q, $C)
end

p = plot()
plot!(p, Ls, ts_sinkhorn; label="Sinkhorn")
plot!(p, Ls, ts_emd;      label="EMD")
xlabel!("#{data points}")
ylabel!("Time (s)")
```

![image](https://user-images.githubusercontent.com/5985769/87777560-9fe0b080-c821-11ea-8ea1-c3024794247f.png)

Did I do anything wrong here?

**Comment by zsteve** [comment]
Hi @xukai92,
Good question and apologies for the slow response. First I just realised that the latest version (with updates) somehow didn't get registered in General. I will fix this soon, but for now please add from Github:
```
pkg> add https://github.com/zsteve/OptimalTransport.jl
```

What I will say about the example you posted is that the value of ϵ (=0.1 in your example) should be relative to the cost matrix `C`, since the entropic OT problem is invariant by a scalar factor. In the current example, I think `C` has entries of order ~10, so ϵ = 0.1 is very small and in fact Sinkhorn fails to converge within 1000 iterations.

I modified your example to the following by scaling with respect to the mean value of `C` (in this case, the effective epsilon gets much larger).
```
ts_sinkhorn = map(Ls) do L
    p, q, C = make_fakedata(dim, L, errorlevel)
    @belapsed sinkhorn($p, $q, $C, $ϵ*mean($C))
end
```
Using this, the results are closer to what you expect.plo
![plot](https://user-images.githubusercontent.com/4413359/88364460-d180dc80-cd37-11ea-9b9a-d2a00c31d7a5.png)

**Comment by xukai92** [comment]
Thanks a lot for the answer. Yes it indeed doesn't converge and taking your suggestion fix the issue. Maybe it's worth to throw a warning if `sinkhorn` fails to converge within the default `maxiter`?

**Comment by zsteve** [comment]
Yes I agree! Indeed that was added in the updated version which I have registered in General now (v0.1.5)
